[build]
  # This tells Netlify where your website files are located
  publish = "Projects/ics new site"
  
  # Since this is a static HTML site, no build command is needed
  command = ""

# Custom headers for better performance and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets for better performance
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache HTML files for shorter periods
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Ensure index.html is served for the root
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

# Custom 404 page (optional)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404